/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VPrincipal.java
 *
 * Created on 27-ene-2011, 10:31:24
 */

package gui;
import aplicacion.*;
import java.awt.Component;
import javax.swing.text.html.HTMLEditorKit;


/**
 *
 * @author grupo2b
 */
public class VAdministrador extends javax.swing.JFrame {
  
    aplicacion.FachadaAplicacion fa;
    UsuarioUSC miembroUSC;
    
    /** Creates new form VPrincipal */
    public VAdministrador(aplicacion.FachadaAplicacion fa) {
        this.fa=fa;
        initComponents();
    }
    
    public void setMiembroUSC(UsuarioUSC usuario){
        this.miembroUSC = usuario;
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCambiarAtributos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonAnhadir = new javax.swing.JButton();
        jTextFieldMatriculaInfraccion = new javax.swing.JTextField();
        jTextFieldDniSaldo = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jButtonModificar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNuevoSaldo = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        panelAzul = new java.awt.Panel();
        jLabelCoche = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jLabelParkingUSC1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parking USC");
        setForeground(new java.awt.Color(51, 204, 255));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setName("vPrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setMaximumSize(new java.awt.Dimension(800, 500));
        background.setMinimumSize(new java.awt.Dimension(800, 500));
        background.setPreferredSize(new java.awt.Dimension(800, 500));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCambiarAtributos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 24)); // NOI18N
        jLabel2.setText("Añadir infraccion");

        jLabel4.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 18)); // NOI18N
        jLabel4.setText("Matricula vehiculo");

        jLabel5.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 18)); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jButtonAnhadir.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAnhadir.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButtonAnhadir.setText("<html>Añadir</html>");
        jButtonAnhadir.setToolTipText("");
        jButtonAnhadir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonAnhadir.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonAnhadir.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonAnhadir.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonAnhadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnhadirActionPerformed(evt);
            }
        });

        jTextFieldMatriculaInfraccion.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jTextFieldMatriculaInfraccion.setBorder(null);
        jTextFieldMatriculaInfraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatriculaInfraccionActionPerformed(evt);
            }
        });

        jTextFieldDniSaldo.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jTextFieldDniSaldo.setBorder(null);
        jTextFieldDniSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDniSaldoActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 24)); // NOI18N
        jLabel7.setText("Modificar saldo");

        jButtonModificar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonModificar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButtonModificar.setText("<html>Modificar</html>");
        jButtonModificar.setToolTipText("");
        jButtonModificar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonModificar.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonModificar.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonModificar.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 18)); // NOI18N
        jLabel8.setText("DNI Miembro USC");

        jTextFieldNuevoSaldo.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jTextFieldNuevoSaldo.setBorder(null);
        jTextFieldNuevoSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNuevoSaldoActionPerformed(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 18)); // NOI18N
        jLabel9.setText("Nuevo saldo");

        javax.swing.GroupLayout jPanelCambiarAtributosLayout = new javax.swing.GroupLayout(jPanelCambiarAtributos);
        jPanelCambiarAtributos.setLayout(jPanelCambiarAtributosLayout);
        jPanelCambiarAtributosLayout.setHorizontalGroup(
            jPanelCambiarAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCambiarAtributosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelCambiarAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCambiarAtributosLayout.createSequentialGroup()
                        .addGroup(jPanelCambiarAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCambiarAtributosLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanelCambiarAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(83, Short.MAX_VALUE))
                    .addGroup(jPanelCambiarAtributosLayout.createSequentialGroup()
                        .addGroup(jPanelCambiarAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNuevoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCambiarAtributosLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldDniSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCambiarAtributosLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jButtonAnhadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldMatriculaInfraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCambiarAtributosLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanelCambiarAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelCambiarAtributosLayout.setVerticalGroup(
            jPanelCambiarAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCambiarAtributosLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanelCambiarAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonAnhadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(jTextFieldMatriculaInfraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addGroup(jPanelCambiarAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addComponent(jTextFieldDniSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(2, 2, 2)
                .addComponent(jTextFieldNuevoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanelCambiarAtributos);

        background.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, -30, 500, 530));

        panelAzul.setBackground(new java.awt.Color(153, 204, 255));
        panelAzul.setForeground(new java.awt.Color(0, 0, 0));
        panelAzul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCoche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/coche.png"))); // NOI18N
        panelAzul.add(jLabelCoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSalir.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButtonSalir.setText("<html>Salir</html>");
        jButtonSalir.setToolTipText("");
        jButtonSalir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonSalir.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonSalir.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonSalir.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        panelAzul.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 90, 40));

        jButtonAtras.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAtras.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButtonAtras.setText("<html>Atrás</html>");
        jButtonAtras.setToolTipText("");
        jButtonAtras.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonAtras.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonAtras.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonAtras.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        panelAzul.add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 90, 40));

        jLabelParkingUSC1.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 36)); // NOI18N
        jLabelParkingUSC1.setText("PARKING USC");
        panelAzul.add(jLabelParkingUSC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 220, -1));

        background.add(panelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Biblioteca Informática");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        // TODO add your handling code here:
        // Se vuelve a instanciar la ventana principal y se asigna el miembro
        VPrincipal vp = new VPrincipal(this.fa);
        vp.setMiembroUSC(this.miembroUSC);
        // La nueva ventana tiene la misma posicion que la anterior
        this.dispose();
        vp.setLocation(this.getLocation());
        vp.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jTextFieldMatriculaInfraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaInfraccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatriculaInfraccionActionPerformed

    private void jButtonAnhadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnhadirActionPerformed
        // TODO add your handling code here:
        Vehiculo vehiculo = new Vehiculo(this.jTextFieldMatriculaInfraccion.getText());
        
        if(fa.getFachadaBaseDatos().anhadirInfraccion(vehiculo) == true){
           /// -------------------- ACTUALIZAR LOS DATOS DEL USUARIO --------------
            this.miembroUSC.setVehiculos(fa.getFachadaBaseDatos().vehiculosUsuario(this.miembroUSC));
           
            
        // Mostrar ventana aviso de anhadido
        VAvisoCompletado vc = new VAvisoCompletado(this.fa, "Infraccion añadida correctamente");
        // La nueva ventana tiene la misma posicion que la anterior
        this.jButtonAtras.doClick();
        vc.setVisible(true);
                }else{
                    // Mostrar ventana aviso de pagado
        VAvisoCompletado vc = new VAvisoCompletado(this.fa, "Matrícula desconocida");
        // La nueva ventana tiene la misma posicion que la anterior
        this.jButtonAtras.doClick();
        vc.setVisible(true);
                }
            
        
        
    }//GEN-LAST:event_jButtonAnhadirActionPerformed

    private void jTextFieldDniSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDniSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDniSaldoActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        
        UsuarioUSC usuario = new UsuarioUSC(this.jTextFieldDniSaldo.getText());
        float saldo =Float.parseFloat( this.jTextFieldNuevoSaldo.getText() );
        
        if(fa.getFachadaBaseDatos().cambiarSaldo(usuario, saldo) == true){
            /// -------------------- ACTUALIZAR LOS DATOS DEL USUARIO --------------
           this.miembroUSC.setSaldo(fa.getFachadaBaseDatos().getUsuario(miembroUSC.getDniUsuario()).getSaldo());
           
        // Mostrar ventana aviso de actualizado
        VAvisoCompletado vc = new VAvisoCompletado(this.fa, "Saldo modificado correctamente");
        // La nueva ventana tiene la misma posicion que la anterior
        this.jButtonAtras.doClick();
        vc.setVisible(true);
                }else{
                    // Mostrar ventana aviso de pagado
        VAvisoCompletado vc = new VAvisoCompletado(this.fa, "DNI no válido");
        // La nueva ventana tiene la misma posicion que la anterior
        this.jButtonAtras.doClick();
        vc.setVisible(true);
                }
        
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jTextFieldNuevoSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNuevoSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNuevoSaldoActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton jButtonAnhadir;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCoche;
    private javax.swing.JLabel jLabelParkingUSC1;
    private javax.swing.JPanel jPanelCambiarAtributos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldDniSaldo;
    private javax.swing.JTextField jTextFieldMatriculaInfraccion;
    private javax.swing.JTextField jTextFieldNuevoSaldo;
    private java.awt.Panel panelAzul;
    // End of variables declaration//GEN-END:variables

    
}
