/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VAutentificacion.java
 *
 * Created on 16-feb-2011, 17:52:08
 */

package gui;

import java.awt.Color;
import baseDatos.*;
import aplicacion.*;
import java.awt.event.FocusEvent;

/**
 *
 * @author grupo2b
 */
public class VAutentificacion extends javax.swing.JDialog {

    aplicacion.FachadaAplicacion fa;
    baseDatos.FachadaBaseDatos fb;
    VPrincipal vp;
    
    /** Creates new form VAutentificacion
     * @param parent
     * @param modal
     * @param fa */
    public VAutentificacion(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa) {
        super(parent, modal);
        this.fa=fa;
        this.fb=fa.getFachadaBaseDatos();
        vp = (VPrincipal) parent;
        initComponents();
        etiquetaFallo.setVisible(false);
        this.btnAceptar.requestFocusInWindow(FocusEvent.Cause.UNKNOWN);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        textoClave = new javax.swing.JPasswordField();
        etiquetaFallo = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelContrasenha = new javax.swing.JLabel();
        textoUsuario = new javax.swing.JTextField();
        jLabelInicioSesion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelUsuario = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inicio de sesión");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 204, 255));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setModal(true);
        setName("VAutentificacion"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setMaximumSize(new java.awt.Dimension(800, 500));
        background.setMinimumSize(new java.awt.Dimension(800, 500));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoClave.setForeground(new java.awt.Color(153, 153, 153));
        textoClave.setText("Contraseña");
        textoClave.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        textoClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textoClaveMousePressed(evt);
            }
        });
        textoClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoClaveActionPerformed(evt);
            }
        });
        background.add(textoClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 704, -1));

        etiquetaFallo.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        etiquetaFallo.setForeground(new java.awt.Color(255, 51, 51));
        etiquetaFallo.setText("Credenciales incorrectas");
        background.add(etiquetaFallo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 420, 20));

        btnAceptar.setBackground(new java.awt.Color(153, 204, 255));
        btnAceptar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        background.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 110, 40));

        btnCancelar.setBackground(new java.awt.Color(153, 204, 255));
        btnCancelar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        background.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 110, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 710, 10));

        jLabelContrasenha.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabelContrasenha.setText("Contraseña");
        background.add(jLabelContrasenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 240, 20));

        textoUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 13)); // NOI18N
        textoUsuario.setForeground(new java.awt.Color(153, 153, 153));
        textoUsuario.setText("Ingrese su nombre de usuario");
        textoUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        textoUsuario.setCaretColor(new java.awt.Color(204, 204, 204));
        textoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textoUsuarioMousePressed(evt);
            }
        });
        textoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuarioActionPerformed(evt);
            }
        });
        background.add(textoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 704, -1));

        jLabelInicioSesion.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 24)); // NOI18N
        jLabelInicioSesion.setText("INICIO DE SESIÓN");
        background.add(jLabelInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 710, 50));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 710, 10));

        jLabelUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabelUsuario.setText("Usuario");
        background.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 240, 20));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
       UsuarioUSC usuario = null;
        
        etiquetaFallo.setVisible(false);
        if(fa.comprobarAutentificacion(textoUsuario.getText(), textoClave.getText()) == null){
             etiquetaFallo.setText("Usuario vetado");
             etiquetaFallo.setVisible(true);
        }
        else if (fa.comprobarAutentificacion(textoUsuario.getText(), textoClave.getText())){
           usuario = fb.validarUsuario(textoUsuario.getText(), textoClave.getText());
           // Asigna los vehiculos correspondientes
           usuario.setVehiculos(fa.getFachadaBaseDatos().vehiculosUsuario(usuario));
           vp.setMiembroUSC(usuario);
           this.dispose();
        }
        else{
            etiquetaFallo.setText("Credenciales incorrectas");
            etiquetaFallo.setVisible(true);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
     System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void textoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuarioActionPerformed

    private void textoUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoUsuarioMousePressed
        // TODO add your handling code here:
        if(textoUsuario.getText().equals("Ingrese su nombre de usuario")){
            textoUsuario.setText("");
            textoUsuario.setForeground(Color.BLACK);
        }
        if((String.valueOf(textoClave.getPassword()).isEmpty())){
            textoClave.setText("Contraseña");
            textoClave.setForeground(Color.GRAY);
        
        }
    }//GEN-LAST:event_textoUsuarioMousePressed

    private void textoClaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoClaveMousePressed
        // TODO add your handling code here:
        if((String.valueOf(textoClave.getPassword())).equals("Contraseña")){
             textoClave.setText("");
             textoClave.setForeground(Color.BLACK);
        }
        if(textoUsuario.getText().isEmpty()){
             textoUsuario.setText("Ingrese su nombre de usuario");
             textoUsuario.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_textoClaveMousePressed

    private void textoClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoClaveActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel etiquetaFallo;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabelContrasenha;
    private javax.swing.JLabel jLabelInicioSesion;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField textoClave;
    private javax.swing.JTextField textoUsuario;
    // End of variables declaration//GEN-END:variables

}
