/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author grupo2b
 */
public class VAvisoCompletado extends javax.swing.JDialog {

    aplicacion.FachadaAplicacion fa;
    /**
     * Creates new form VAviso
     */
    public VAvisoCompletado(aplicacion.FachadaAplicacion fa, String textoMostrado) {
        initComponents();
        this.fa = fa;
        this.setLocationRelativeTo(null);
        this.jLabelTextoMostrado.setText(textoMostrado);
        this.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jButttonCerrar = new javax.swing.JButton();
        jLabelTextoMostrado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 250));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setMaximumSize(new java.awt.Dimension(500, 250));
        background.setMinimumSize(new java.awt.Dimension(500, 250));
        background.setPreferredSize(new java.awt.Dimension(500, 250));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButttonCerrar.setBackground(new java.awt.Color(153, 204, 255));
        jButttonCerrar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButttonCerrar.setText("Ok");
        jButttonCerrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButttonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButttonCerrarActionPerformed(evt);
            }
        });
        background.add(jButttonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 130, 40));

        jLabelTextoMostrado.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabelTextoMostrado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.add(jLabelTextoMostrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButttonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButttonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButttonCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton jButttonCerrar;
    private javax.swing.JLabel jLabelTextoMostrado;
    // End of variables declaration//GEN-END:variables
}
