/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VPrincipal.java
 *
 * Created on 27-ene-2011, 10:31:24
 */

package gui;
import aplicacion.*;
import java.awt.Component;
import java.util.ArrayList;
import java.sql.Timestamp;
import java.util.concurrent.TimeUnit;
import javax.swing.text.html.HTMLEditorKit;


/**
 *
 * @author grupo2b
 */
public class VMisReservas extends javax.swing.JFrame {
  
    aplicacion.FachadaAplicacion fa;
    UsuarioUSC miembroUSC;
    private ArrayList<Reservar> reservasTotales;
    private Reservar reservar;
    private float costeTotal;
    
    /** Creates new form VPrincipal */
    public VMisReservas(aplicacion.FachadaAplicacion fa) {
        this.fa=fa;
        initComponents();
    }
    
    public void setMiembroUSC(UsuarioUSC usuario){
        this.miembroUSC = usuario;
        actualizarSaldo();

        // Obtiene el año, mes y día de la fecha actual
        Timestamp fechaActual = new Timestamp(System.currentTimeMillis());
        
          // Usa un HTMLEditorKit para renderizar HTML en el JEditorPane
        this.jEditorPaneReservasAntiguas.setEditorKit(new HTMLEditorKit());
        this.jEditorPaneReservasActivas.setEditorKit(new HTMLEditorKit());
        
        reservasTotales = fa.getFachadaBaseDatos().reservasTotales(usuario);
        String textoTotales = "<html> ";
        String textoActivas = "<html> ";
        for(Reservar reserva : reservasTotales){
            
            
        // Calcular la cantidad de horas entre las dos fechas
        long diferenciaEnMilisegundos = reserva.getFechaFin().getTime() - reserva.getFechaInicio().getTime();
        long horas = TimeUnit.MILLISECONDS.toHours(diferenciaEnMilisegundos);
        
         // Mostrar vehiculo, parking, fechas y precio
         float coste = reserva.getPrecioHora() * horas;
         costeTotal = coste;
           
         
           String texto = "";
           texto += "Campus: " + reserva.getCampus().getNombre() + "<br>";
           texto += "Centro: " + reserva.getCentro().getNombre() + "<br>";
           texto += "Fecha Inicio: " + reserva.getFechaInicio() + "<br>";
           texto += "Fecha Fin: " + reserva.getFechaFin() + "<br>";
           texto += "Numero de plaza: " + reserva.getIdPlaza() + "<br>";
           texto += "Precio pagado: " + costeTotal;
            
           
           if(reserva.getFechaFin().after(fechaActual)){
               textoActivas += texto;
           }else{
                   textoTotales += texto;
           }
        }
        
        textoActivas += "</html>";
        textoTotales += "</html>";
        this.jEditorPaneReservasAntiguas.setText(textoTotales);
        this.jEditorPaneReservasActivas.setText(textoActivas);
        
    }
    
    public void actualizarSaldo(){
        this.jLabelSaldo.setText("Saldo: " + this.miembroUSC.getSaldo() + "€");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelMostrarReservas = new javax.swing.JPanel();
        jLabelSaldo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPaneReservasAntiguas = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPaneReservasActivas = new javax.swing.JEditorPane();
        panelAzul = new java.awt.Panel();
        jLabelParkingUSC = new javax.swing.JLabel();
        jLabelCoche = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parking USC");
        setForeground(new java.awt.Color(51, 204, 255));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setName("vPrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setMaximumSize(new java.awt.Dimension(800, 500));
        background.setMinimumSize(new java.awt.Dimension(800, 500));
        background.setPreferredSize(new java.awt.Dimension(800, 500));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMostrarReservas.setBackground(new java.awt.Color(255, 255, 255));

        jLabelSaldo.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabelSaldo.setText("Saldo: ");

        jLabel1.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 24)); // NOI18N
        jLabel1.setText("Reservas activas");

        jLabel2.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 24)); // NOI18N
        jLabel2.setText("Reservas antiguas");

        jScrollPane1.setViewportView(jEditorPaneReservasAntiguas);

        jScrollPane2.setViewportView(jEditorPaneReservasActivas);

        javax.swing.GroupLayout jPanelMostrarReservasLayout = new javax.swing.GroupLayout(jPanelMostrarReservas);
        jPanelMostrarReservas.setLayout(jPanelMostrarReservasLayout);
        jPanelMostrarReservasLayout.setHorizontalGroup(
            jPanelMostrarReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMostrarReservasLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanelMostrarReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMostrarReservasLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMostrarReservasLayout.createSequentialGroup()
                        .addGroup(jPanelMostrarReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMostrarReservasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(166, 166, 166))))
        );
        jPanelMostrarReservasLayout.setVerticalGroup(
            jPanelMostrarReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMostrarReservasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("tab1", jPanelMostrarReservas);

        background.add(jTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, -30, 500, 530));

        panelAzul.setBackground(new java.awt.Color(153, 204, 255));
        panelAzul.setForeground(new java.awt.Color(0, 0, 0));
        panelAzul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelParkingUSC.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 36)); // NOI18N
        jLabelParkingUSC.setText("PARKING USC");
        panelAzul.add(jLabelParkingUSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 220, -1));

        jLabelCoche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/coche.png"))); // NOI18N
        panelAzul.add(jLabelCoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSalir.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButtonSalir.setText("<html>Salir</html>");
        jButtonSalir.setToolTipText("");
        jButtonSalir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonSalir.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonSalir.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonSalir.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        panelAzul.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 90, 40));

        jButtonAtras.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAtras.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButtonAtras.setText("<html>Atrás</html>");
        jButtonAtras.setToolTipText("");
        jButtonAtras.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonAtras.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonAtras.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonAtras.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        panelAzul.add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 90, 40));

        background.add(panelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Biblioteca Informática");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        // TODO add your handling code here:
        // Se vuelve a instanciar la ventana principal y se asigna el miembro
        VPrincipal vp = new VPrincipal(this.fa);
        vp.setMiembroUSC(this.miembroUSC);
        // La nueva ventana tiene la misma posicion que la anterior
        this.dispose();
        vp.setLocation(this.getLocation());
        vp.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JEditorPane jEditorPaneReservasActivas;
    private javax.swing.JEditorPane jEditorPaneReservasAntiguas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCoche;
    private javax.swing.JLabel jLabelParkingUSC;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JPanel jPanelMostrarReservas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane;
    private java.awt.Panel panelAzul;
    // End of variables declaration//GEN-END:variables

  
    
}
