/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VPrincipal.java
 *
 * Created on 27-ene-2011, 10:31:24
 */

package gui;
import aplicacion.*;


/**
 *
 * @author grupo2b
 */
public class VPrincipal extends javax.swing.JFrame {
  
    aplicacion.FachadaAplicacion fa;
    UsuarioUSC miembroUSC;
    
    /** Creates new form VPrincipal */
    public VPrincipal(aplicacion.FachadaAplicacion fa) {
        this.fa=fa;
        initComponents();
    }
    
    public void setMiembroUSC(UsuarioUSC usuario){
        this.miembroUSC = usuario;
        actualizarRol();
    }
    
    private void actualizarRol(){
        if(this.miembroUSC.getRol().equals("administrador")){
            jButtonModoAdministrador.setVisible(true);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jButtonModoAdministrador = new javax.swing.JButton();
        jButtonAjustes = new javax.swing.JButton();
        panelAzul = new java.awt.Panel();
        jLabelParkingUSC = new javax.swing.JLabel();
        jLabelCoche = new javax.swing.JLabel();
        jButtonIngresarVehiculo = new javax.swing.JButton();
        jButtonRetirarVehiculo = new javax.swing.JButton();
        jButtonMisReservas = new javax.swing.JButton();
        jButtonReservar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonVerParking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parking USC");
        setForeground(new java.awt.Color(51, 204, 255));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setName("vPrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setMaximumSize(new java.awt.Dimension(800, 500));
        background.setMinimumSize(new java.awt.Dimension(800, 500));
        background.setPreferredSize(new java.awt.Dimension(800, 500));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonModoAdministrador.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButtonModoAdministrador.setText("<html><u>Modo administrador</u></html>");
        jButtonModoAdministrador.setBorderPainted(false);
        jButtonModoAdministrador.setContentAreaFilled(false);
        jButtonModoAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModoAdministradorActionPerformed(evt);
            }
        });
        background.add(jButtonModoAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, 40));
        jButtonModoAdministrador.setVisible(false);

        jButtonAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/ajustes.png"))); // NOI18N
        jButtonAjustes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjustesActionPerformed(evt);
            }
        });
        background.add(jButtonAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 55, 55));

        panelAzul.setBackground(new java.awt.Color(153, 204, 255));
        panelAzul.setForeground(new java.awt.Color(0, 0, 0));
        panelAzul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelParkingUSC.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 36)); // NOI18N
        jLabelParkingUSC.setText("PARKING USC");
        panelAzul.add(jLabelParkingUSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 220, -1));

        jLabelCoche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/coche.png"))); // NOI18N
        panelAzul.add(jLabelCoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jButtonIngresarVehiculo.setBackground(new java.awt.Color(204, 204, 204));
        jButtonIngresarVehiculo.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButtonIngresarVehiculo.setText("<html>Ingresar<br>\nvehículo</html>");
        jButtonIngresarVehiculo.setToolTipText("");
        jButtonIngresarVehiculo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonIngresarVehiculo.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonIngresarVehiculo.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonIngresarVehiculo.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonIngresarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarVehiculoActionPerformed(evt);
            }
        });
        panelAzul.add(jButtonIngresarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 90, 40));

        jButtonRetirarVehiculo.setBackground(new java.awt.Color(204, 204, 204));
        jButtonRetirarVehiculo.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButtonRetirarVehiculo.setText("<html>Retirar<br> vehículo</html>");
        jButtonRetirarVehiculo.setToolTipText("");
        jButtonRetirarVehiculo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonRetirarVehiculo.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonRetirarVehiculo.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonRetirarVehiculo.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonRetirarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirarVehiculoActionPerformed(evt);
            }
        });
        panelAzul.add(jButtonRetirarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 90, 40));

        jButtonMisReservas.setBackground(new java.awt.Color(204, 204, 204));
        jButtonMisReservas.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButtonMisReservas.setText("<html>Mis<br>reservas</html>");
        jButtonMisReservas.setToolTipText("");
        jButtonMisReservas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonMisReservas.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonMisReservas.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonMisReservas.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonMisReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMisReservasActionPerformed(evt);
            }
        });
        panelAzul.add(jButtonMisReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 90, 40));

        jButtonReservar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonReservar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButtonReservar.setText("<html>Reservar</html>");
        jButtonReservar.setToolTipText("");
        jButtonReservar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonReservar.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonReservar.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonReservar.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservarActionPerformed(evt);
            }
        });
        panelAzul.add(jButtonReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 90, 40));

        jButtonSalir.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSalir.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButtonSalir.setText("<html>Salir</html>");
        jButtonSalir.setToolTipText("");
        jButtonSalir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonSalir.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonSalir.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonSalir.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        panelAzul.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 90, 40));

        jButtonVerParking.setBackground(new java.awt.Color(204, 204, 204));
        jButtonVerParking.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButtonVerParking.setText("<html>Ver<br> Parking</html>");
        jButtonVerParking.setToolTipText("");
        jButtonVerParking.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonVerParking.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonVerParking.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonVerParking.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonVerParking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerParkingActionPerformed(evt);
            }
        });
        panelAzul.add(jButtonVerParking, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 90, 40));

        background.add(panelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Biblioteca Informática");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarVehiculoActionPerformed
        // TODO add your handling code here:
        VIngresarVehiculo vingreso = new VIngresarVehiculo(this.fa);
        vingreso.setMiembroUSC(this.miembroUSC);
        this.dispose();
        // La nueva ventana tiene la misma localizacion que la anterior 
        vingreso.setLocation(this.getLocation());
        vingreso.setVisible(true);
    }//GEN-LAST:event_jButtonIngresarVehiculoActionPerformed

    private void jButtonModoAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModoAdministradorActionPerformed
        // TODO add your handling code here:
        VAdministrador vadmin = new VAdministrador(this.fa);
        vadmin.setMiembroUSC(this.miembroUSC);
        this.dispose();
        // La nueva ventana tiene la misma localizacion que la anterior 
        vadmin.setLocation(this.getLocation());
        vadmin.setVisible(true);
    }//GEN-LAST:event_jButtonModoAdministradorActionPerformed

    private void jButtonAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjustesActionPerformed
        // TODO add your handling code here:
        // Se instancia la nueva ventana y se asigna el miembro 
        VAjustes vajustes = new VAjustes(this.fa);
        vajustes.setMiembroUSC(this.miembroUSC);
        this.dispose();
        // La nueva ventana tiene la misma localizacion que la anterior 
        vajustes.setLocation(this.getLocation());
        vajustes.setVisible(true);
    }//GEN-LAST:event_jButtonAjustesActionPerformed

    private void jButtonVerParkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerParkingActionPerformed
        // TODO add your handling code here:
        // Se instancia la nueva ventana y se asigna el miembro 
        VVerParking vverparking = new VVerParking(this.fa);
        vverparking.setMiembroUSC(this.miembroUSC);
        this.dispose();
        // La nueva ventana tiene la misma localizacion que la anterior 
        vverparking.setLocation(this.getLocation());
        vverparking.setVisible(true);
    }//GEN-LAST:event_jButtonVerParkingActionPerformed

    private void jButtonRetirarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetirarVehiculoActionPerformed
        // TODO add your handling code here:
        // Se instancia la nueva ventana y se asigna el miembro 
        VRetirarVehiculo vretirar = new VRetirarVehiculo(this.fa);
        vretirar.setMiembroUSC(this.miembroUSC);
        this.dispose();
        // La nueva ventana tiene la misma localizacion que la anterior 
        vretirar.setLocation(this.getLocation());
        vretirar.setVisible(true);
    }//GEN-LAST:event_jButtonRetirarVehiculoActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservarActionPerformed
        // TODO add your handling code here:
        VReservar vreservar = new VReservar(this.fa);
        this.dispose();
        // La nueva ventana tiene la misma localizacion que la anterior 
        vreservar.setLocation(this.getLocation());
        vreservar.setMiembroUSC(this.miembroUSC);
        vreservar.setVisible(true);
    }//GEN-LAST:event_jButtonReservarActionPerformed

    private void jButtonMisReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMisReservasActionPerformed
        // TODO add your handling code here:
        VMisReservas vreservas = new VMisReservas(this.fa);
        vreservas.setMiembroUSC(this.miembroUSC);
        this.dispose();
        // La nueva ventana tiene la misma localizacion que la anterior 
        vreservas.setLocation(this.getLocation());
        vreservas.setVisible(true);
    }//GEN-LAST:event_jButtonMisReservasActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton jButtonAjustes;
    private javax.swing.JButton jButtonIngresarVehiculo;
    private javax.swing.JButton jButtonMisReservas;
    private javax.swing.JButton jButtonModoAdministrador;
    private javax.swing.JButton jButtonReservar;
    private javax.swing.JButton jButtonRetirarVehiculo;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVerParking;
    private javax.swing.JLabel jLabelCoche;
    private javax.swing.JLabel jLabelParkingUSC;
    private java.awt.Panel panelAzul;
    // End of variables declaration//GEN-END:variables

  
}
