/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VPrincipal.java
 *
 * Created on 27-ene-2011, 10:31:24
 */

package gui;
import aplicacion.*;
import java.awt.Component;
import java.util.ArrayList;
import java.sql.Timestamp;
import java.util.concurrent.TimeUnit;


/**
 *
 * @author grupo2b
 */
public class VRetirarVehiculo extends javax.swing.JFrame {
  
    aplicacion.FachadaAplicacion fa;
    UsuarioUSC miembroUSC;
    private ArrayList<Aparcar> vehiculosAparcados;
    private Aparcar aparcar;
    private float costeTotal;
    
    /** Creates new form VPrincipal */
    public VRetirarVehiculo(aplicacion.FachadaAplicacion fa) {
        this.fa=fa;
        initComponents();
    }
    
    public void setMiembroUSC(UsuarioUSC usuario){
        this.miembroUSC = usuario;
        actualizarSaldo();
        vehiculosAparcados = fa.getFachadaBaseDatos().vehiculosAparcados(usuario);
        for(Aparcar ap : vehiculosAparcados){
            String texto = "<html>";
            texto += ap.getVehiculo().getTipo() + ": <br>";
            texto += "Matricula: " + ap.getVehiculo().getMatricula()  + " <br>";
            texto +=  "Parking: " + ap.getCentro().getNombre() + " <br>";
            texto +=  "Fecha Entrada: " + ap.getFechaEntrada() + "</html>";
            this.jComboBoxSelecionarVehiculo.addItem(texto);
        }
    }
    
    public void actualizarSaldo(){
        this.jLabelSaldo.setText("Saldo: " + this.miembroUSC.getSaldo() + "€");
        this.jLabelSaldo1.setText("Saldo: " + this.miembroUSC.getSaldo() + "€");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelSelecVehiculo = new javax.swing.JPanel();
        jLabelSaldo = new javax.swing.JLabel();
        jComboBoxSelecionarVehiculo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonSeleccionar = new javax.swing.JButton();
        jPanelPagar = new javax.swing.JPanel();
        jLabelSaldo1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonPagar = new javax.swing.JButton();
        jLabelSeleccionado = new javax.swing.JLabel();
        jLabelSaldoInsuficiente = new javax.swing.JLabel();
        panelAzul = new java.awt.Panel();
        jLabelParkingUSC = new javax.swing.JLabel();
        jLabelCoche = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parking USC");
        setForeground(new java.awt.Color(51, 204, 255));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setName("vPrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setMaximumSize(new java.awt.Dimension(800, 500));
        background.setMinimumSize(new java.awt.Dimension(800, 500));
        background.setPreferredSize(new java.awt.Dimension(800, 500));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSelecVehiculo.setBackground(new java.awt.Color(255, 255, 255));

        jLabelSaldo.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabelSaldo.setText("Saldo: ");

        jComboBoxSelecionarVehiculo.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jComboBoxSelecionarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelecionarVehiculoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 24)); // NOI18N
        jLabel1.setText("Seleccionar Vehículo");

        jButtonSeleccionar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSeleccionar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButtonSeleccionar.setText("<html>Seleccionar</html>");
        jButtonSeleccionar.setToolTipText("");
        jButtonSeleccionar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonSeleccionar.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonSeleccionar.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonSeleccionar.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSelecVehiculoLayout = new javax.swing.GroupLayout(jPanelSelecVehiculo);
        jPanelSelecVehiculo.setLayout(jPanelSelecVehiculoLayout);
        jPanelSelecVehiculoLayout.setHorizontalGroup(
            jPanelSelecVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelecVehiculoLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSelecVehiculoLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanelSelecVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSelecVehiculoLayout.createSequentialGroup()
                        .addGroup(jPanelSelecVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxSelecionarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSelecVehiculoLayout.createSequentialGroup()
                        .addComponent(jButtonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jPanelSelecVehiculoLayout.setVerticalGroup(
            jPanelSelecVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelecVehiculoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxSelecionarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jButtonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        jTabbedPane.addTab("tab1", jPanelSelecVehiculo);

        jPanelPagar.setBackground(new java.awt.Color(255, 255, 255));

        jLabelSaldo1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabelSaldo1.setText("Saldo: ");

        jLabel2.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 24)); // NOI18N
        jLabel2.setText("Vehículo Seleccionado");

        jButtonPagar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonPagar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButtonPagar.setText("<html>Pagar</html>");
        jButtonPagar.setToolTipText("");
        jButtonPagar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonPagar.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonPagar.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonPagar.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagarActionPerformed(evt);
            }
        });

        jLabelSeleccionado.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabelSeleccionado.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelSaldoInsuficiente.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabelSaldoInsuficiente.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanelPagarLayout = new javax.swing.GroupLayout(jPanelPagar);
        jPanelPagar.setLayout(jPanelPagarLayout);
        jPanelPagarLayout.setHorizontalGroup(
            jPanelPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPagarLayout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(jLabelSaldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanelPagarLayout.createSequentialGroup()
                .addGroup(jPanelPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPagarLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel2))
                    .addGroup(jPanelPagarLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabelSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPagarLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabelSaldoInsuficiente, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanelPagarLayout.setVerticalGroup(
            jPanelPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPagarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelSaldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabelSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanelPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSaldoInsuficiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81))
        );

        jTabbedPane.addTab("tab1", jPanelPagar);

        background.add(jTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, -30, 500, 530));

        panelAzul.setBackground(new java.awt.Color(153, 204, 255));
        panelAzul.setForeground(new java.awt.Color(0, 0, 0));
        panelAzul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelParkingUSC.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 36)); // NOI18N
        jLabelParkingUSC.setText("PARKING USC");
        panelAzul.add(jLabelParkingUSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 220, -1));

        jLabelCoche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/coche.png"))); // NOI18N
        panelAzul.add(jLabelCoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSalir.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButtonSalir.setText("<html>Salir</html>");
        jButtonSalir.setToolTipText("");
        jButtonSalir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonSalir.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonSalir.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonSalir.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        panelAzul.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 90, 40));

        jButtonAtras.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAtras.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButtonAtras.setText("<html>Atrás</html>");
        jButtonAtras.setToolTipText("");
        jButtonAtras.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonAtras.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonAtras.setMinimumSize(new java.awt.Dimension(90, 40));
        jButtonAtras.setPreferredSize(new java.awt.Dimension(90, 40));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        panelAzul.add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 90, 40));

        background.add(panelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Biblioteca Informática");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        // TODO add your handling code here:
        // Se vuelve a instanciar la ventana principal y se asigna el miembro
        VPrincipal vp = new VPrincipal(this.fa);
        vp.setMiembroUSC(this.miembroUSC);
        // La nueva ventana tiene la misma posicion que la anterior
        this.dispose();
        vp.setLocation(this.getLocation());
        vp.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarActionPerformed
        // TODO add your handling code here:
        // Boton de seleccionar vehiculo
        // Cambia de pestanha
        // Obtener el componente de la segunda pestaña
        Component componente = this.jTabbedPane.getComponentAt(1);

        // Cambiar a la segunda pestaña
        this.jTabbedPane.setSelectedComponent(componente);
        
        // Calcular la cantidad de horas entre las dos fechas
        long diferenciaEnMilisegundos = aparcar.getFechaSalida().getTime() - aparcar.getFechaEntrada().getTime();
        long horas = TimeUnit.MILLISECONDS.toHours(diferenciaEnMilisegundos);
        
        // Mostrar vehiculo, parking, fechas y precio
        float coste = aparcar.getPrecioHora() * horas;
        costeTotal = coste;
        
        String texto = "<html>";
            texto += aparcar.getVehiculo().getTipo() + ": <br>";
            texto += "Matricula: " + aparcar.getVehiculo().getMatricula()  + " <br>";
            texto +=  "Parking: " + aparcar.getCentro().getNombre() + " <br>";
            texto +=  "Fecha Entrada: " + aparcar.getFechaEntrada()  + " <br>";
            texto +=  "Fecha Salida: " + aparcar.getFechaSalida()  + " <br>";
            texto +=  "Tiempo total: " + horas  + "horas <br>";
            texto +=  "Precio/Hora: " + aparcar.getPrecioHora()  + " <br>";
            texto +=  "Precio total: " + coste  + " </html>";
        
        this.jLabelSeleccionado.setText(texto);

    }//GEN-LAST:event_jButtonSeleccionarActionPerformed

    private void jComboBoxSelecionarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelecionarVehiculoActionPerformed
        // TODO add your handling code here:
        // Obtiene el año, mes y día de la fecha actual
        Timestamp fechaActual = new Timestamp(System.currentTimeMillis());
        
        // Se actualiza la fecha de salida del vehiculo seleccionado
        
        String elementoSeleccionado = (String) jComboBoxSelecionarVehiculo.getSelectedItem();
        for(Vehiculo v : miembroUSC.getVehiculos()){
            if(elementoSeleccionado.contains(v.getMatricula())){
                for(Aparcar ap : vehiculosAparcados){
                    if(ap.getVehiculo().getMatricula().equals(v.getMatricula())){
                        ap.setFechaSalida(fechaActual);
                        aparcar = ap;
                    }
                }
            }
        }
        
    }//GEN-LAST:event_jComboBoxSelecionarVehiculoActionPerformed

    private void jButtonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagarActionPerformed
        // TODO add your handling code here:
        if(miembroUSC.getSaldo() > costeTotal){
            // Retirar el vehiculo de la relacion
            fa.getFachadaBaseDatos().retirarVehiculoAparcado(aparcar);
            // Actualizar el saldo
            if(fa.getFachadaBaseDatos().cambiarSaldo(miembroUSC, miembroUSC.getSaldo()-costeTotal) == true){
                /// -------------------- ACTUALIZAR LOS DATOS DEL USUARIO --------------
           this.miembroUSC.setSaldo(fa.getFachadaBaseDatos().getUsuario(miembroUSC.getDniUsuario()).getSaldo());
            // Mostrar ventana aviso de pagado
           VAvisoCompletado vc = new VAvisoCompletado(this.fa, "Vehiculo retirado correctamente");
        // La nueva ventana tiene la misma posicion que la anterior
        this.jButtonAtras.doClick();
        vc.setVisible(true);
            }
            
            
            
        } else{
            
            // Mostrar ventana aviso de saldo insuficiente
           VAvisoCompletado vc = new VAvisoCompletado(this.fa, "<html>No se puede retirar el vehículo <br> Saldo insuficiente </html>");
        // La nueva ventana tiene la misma posicion que la anterior
        this.jButtonAtras.doClick();
        vc.setVisible(true);
        }
        
    }//GEN-LAST:event_jButtonPagarActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonPagar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSeleccionar;
    private javax.swing.JComboBox<String> jComboBoxSelecionarVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCoche;
    private javax.swing.JLabel jLabelParkingUSC;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JLabel jLabelSaldo1;
    private javax.swing.JLabel jLabelSaldoInsuficiente;
    private javax.swing.JLabel jLabelSeleccionado;
    private javax.swing.JPanel jPanelPagar;
    private javax.swing.JPanel jPanelSelecVehiculo;
    private javax.swing.JTabbedPane jTabbedPane;
    private java.awt.Panel panelAzul;
    // End of variables declaration//GEN-END:variables

  
}
